# Generated by Django 5.2 on 2025-04-17 18:25


from django.db import migrations


def convert_cartitem_prices_to_cents(apps, schema_editor):
    CartItem = apps.get_model("carts", "CartItem")
    for item in CartItem.objects.all():
        item.total_price = item.toy.price * item.quantity
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_alter_cartitem_total_price"),
    ]

    operations = [
        migrations.RunPython(convert_cartitem_prices_to_cents),
    ]
