# Generated by Django 5.1.7 on 2025-04-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='toys.toy'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlists.wishlist'),
        ),
    ]
