# Generated by Django 5.2 on 2025-04-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_alter_toy_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
