# Generated by Django 5.2 on 2025-04-17 18:25

from django.db import migrations


def convert_prices_to_cents(apps, schema_editor):
    Toy = apps.get_model("toys", "Toy")
    for toy in Toy.objects.all():
        if toy.price is not None:
            toy.price = int(toy.price * 100)
            toy.save()


class Migration(migrations.Migration):
    dependencies = [
        ("toys", "0005_alter_toy_price"),
    ]

    operations = [
        migrations.RunPython(convert_prices_to_cents),
    ]
