# Generated by Django 5.2 on 2025-04-17 17:57

from django.db import migrations


def convert_total_price_to_cents(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.all():
        if order.total_price is not None:
            order.total_price = int(order.total_price * 100)
            order.save()


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_total_price"),
    ]

    operations = [
        migrations.RunPython(convert_total_price_to_cents),
    ]
