# Generated by Django 5.2 on 2025-04-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_convert_cartitem_to_cents'),
        ('orders', '0004_convert_total_price_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.cart'),
        ),
    ]
